terraform:
  outputContractVersion: "v1"
  helmValues:
    observability:
      grafana:
        domainName: "observe.ops.example.com"
        tls:
          certificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/xxxxxx"
  dnsContract:
    observability_domain_name: "grafana.gokulakrishnanr.com"
    acm_certificate_arn: "arn:aws:acm:us-east-1:123456789012:certificate/xxxxxx"

grafana:
  ingress:
    enabled: true
