from typing import Iterable, Protocol

from opscopilot_db import models


class SessionRepository(Protocol):
    def create(self, session: models.Session) -> models.Session: ...

    def get(self, session_id: str) -> models.Session | None: ...

    def list(self, limit: int | None = None, offset: int = 0) -> Iterable[models.Session]: ...

    def update(self, session: models.Session) -> models.Session: ...

    def delete(self, session_id: str) -> None: ...


class MessageRepository(Protocol):
    def create(self, message: models.Message) -> models.Message: ...

    def get(self, message_id: str) -> models.Message | None: ...

    def list_by_session(self, session_id: str) -> Iterable[models.Message]: ...


class AgentRunRepository(Protocol):
    def create(self, agent_run: models.AgentRun) -> models.AgentRun: ...

    def get(self, agent_run_id: str) -> models.AgentRun | None: ...

    def list_by_session(self, session_id: str) -> Iterable[models.AgentRun]: ...

    def update(self, agent_run: models.AgentRun) -> models.AgentRun: ...


class LlmCallRepository(Protocol):
    def create(self, llm_call: models.LlmCall) -> models.LlmCall: ...

    def list_by_run(self, agent_run_id: str) -> Iterable[models.LlmCall]: ...


class ToolCallRepository(Protocol):
    def create(self, tool_call: models.ToolCall) -> models.ToolCall: ...

    def list_by_run(self, agent_run_id: str) -> Iterable[models.ToolCall]: ...


class BudgetEventRepository(Protocol):
    def create(self, budget_event: models.BudgetEvent) -> models.BudgetEvent: ...

    def list_by_run(self, agent_run_id: str) -> Iterable[models.BudgetEvent]: ...
